version: '3'

services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynetworks
  jenkins:
    image: jenkins/jenkins:2.263.1-lts-slim
    volumes:
      - $HOME/.gradle:/var/jenkins_home/.gradle
      - $HOME/.m2:/var/jenkins_home/.m2
    ports:
      - 8080:8080
    networks:
      - mynetworks

networks:
  mynetworks: